version: "3.8"

services:

#  mysql:
#    platform: linux/x86_64
#    image: mysql:8.0.25
#    container_name: mysql
#    restart: unless-stopped
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_DATABASE=moviesdb
#      - MYSQL_ROOT_PASSWORD=secret
#    healthcheck:
#      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
#      start_period: 30s

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
#    container_name: elasticsearch
#    restart: unless-stopped
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      cluster.name: docker-es-cluster
#      discovery.type: single-node
#      bootstrap.memory_lock: "true"
#      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    healthcheck:
#      test: "curl -f http://localhost:9200 || exit 1"
#      start_period: 30s
#
#  logstash:
#    image: docker.elastic.co/logstash/logstash:7.13.1
#    container_name: logstash
#    restart: unless-stopped
#    ports:
#      - "5044:5044"
#    volumes:
#      - ./logstash/pipeline:/usr/share/logstash/pipeline/
#    depends_on:
#      - elasticsearch
#    healthcheck:
#      test: "curl -f http://localhost:9600 || exit 1"
#      start_period: 30s
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.13.1
#    container_name: kibana
#    restart: unless-stopped
#    ports:
#      - "5601:5601"
#    environment:
#      ELASTICSEARCH_URL: http://elasticsearch:9200
#    depends_on:
#      - elasticsearch
#    healthcheck:
#      test: "curl -f http://localhost:5601 || exit 1"
#      start_period: 30s
#
#  filebeat:
#    build: filebeat
#    container_name: filebeat
#    restart: unless-stopped
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /var/lib/docker/containers:/usr/share/dockerlogs/data:ro
#    depends_on:
#      - elasticsearch
#      - logstash

  prometheus:
    image: prom/prometheus:v2.27.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9090" ]
      start_period: 30s

  grafana:
    image: grafana/grafana:8.0.1
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "3000" ]
      start_period: 30s

  config-server:
    container_name: config-server
    build:
      context: config-server
      dockerfile: Dockerfile
    image: config-server:latest
    ports:
      - 8888:8888
    volumes:
      - "~/workspace/git/cinema-app-config:/config"
    environment:
      spring.cloud.config.server.gituri: file://config/cinema-app-config
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      test: "curl --fail --silent config-server:8888/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

  eureka-server:
    container_name: eureka-server
    build:
      context: eureka-discovery
      dockerfile: Dockerfile
    image: eureka-server:latest
    ports:
      - 8761:8761
    environment:
      spring.cloud.config.uri: http://config-server:8888
      eureka.instance.hostname: eureka-server
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    depends_on:
      - config-server
    healthcheck:
      test: "curl --fail --silent eureka-server:8761/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

#  movies-api:
#    container_name: movies-api
#    build:
#      context: movies-api
#      dockerfile: Dockerfile
#    image: movies-api:latest
#    ports:
#      - 8081:8081
#    environment:
#      spring.cloud.config.uri: http://config-server:8888
#      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
#    depends_on:
#      - eureka-server
#      - reviews-api
#    healthcheck:
#      test: "curl --fail --silent movies-api:8081/actuator/health | grep UP || exit 1"
#      interval: 20s
#      timeout: 5s
#      retries: 5
#      start_period: 40s

  reviews-api:
    container_name: reviews-api
    build:
      context: reviews-api
      dockerfile: Dockerfile
    image: reviews-api:latest
    ports:
      - 8082:8082
    environment:
      spring.cloud.config.uri: http://config-server:8888
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    healthcheck:
      test: "curl --fail --silent reviews-api:8082/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

#  zuul-gateway:
#    container_name: zuul-gateway
#    build:
#      context: zuul-gateway
#      dockerfile: Dockerfile
#    image: zuul-gateway:latest
#    ports:
#      - 8762:8762
#    environment:
#      spring.cloud.config.uri: http://config-server:8888
#      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
#    depends_on:
#      - eureka-server
#    healthcheck:
#      test: "curl --fail --silent zuul-gateway:8762/actuator/health | grep UP || exit 1"
#      interval: 20s
#      timeout: 5s
#      retries: 5
#      start_period: 40s