{
 "title": "reviews-api-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "timeRate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "API Calls",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"reviews-api\",method=~\".+\",status=~\"2.+\",uri=~\"/reviews.*\"}[$timeRate]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"reviews-api\",method=~\".+\",status!~\"2.+\",uri=~\"/reviews.*\"}[$timeRate]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"reviews-api\"} * 100",
     "legendFormat": "reviews-api"
    }
   ]
  },
  {
   "title": "GET /api/reviews",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"reviews-api\",method=\"GET\",status=\"200\",uri=\"/reviews\"}[$timeRate]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"reviews-api\",method=\"GET\",status!=\"200\",uri=\"/reviews\"}[$timeRate]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "GET /api/reviews/{imdb}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"reviews-api\",method=\"GET\",status=\"200\",uri=\"/reviews/{movieID}\"}[$timeRate]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"reviews-api\",method=\"GET\",status!=\"200\",uri=\"/reviews/{movieID}\"}[$timeRate]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "POST /api/reviews",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"reviews-api\",method=\"POST\",status=\"201\",uri=\"/reviews\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"reviews-api\",method=\"POST\",status!=\"201\",uri=\"/reviews\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "DELETE /api/reviews/{imdb}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"reviews-api\",method=\"DELETE\",status=\"200\",uri=\"/reviews/{movieID}\"}[$timeRate]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"reviews-api\",method=\"DELETE\",status!=\"200\",uri=\"/reviews/{movieID}\"}[$timeRate]))",
     "legendFormat": "ERROR"
    }
   ]
  }
 ]
}